# Generated by Django 3.2.4 on 2021-07-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date_added',)},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
